### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by BigstickCarpet** [chaijs/chai-fs#21]
The [`chai-fs` package on npm](https://www.npmjs.com/package/chai-fs) hasn't been updated since the project was transferred from @Bartvds to @chaijs/chai two years ago.  😩

@keithamus - Not sure what exactly needs to be done to get the npm package updated.  I'm happy to help if I can.

**Comment by BigstickCarpet** [comment]
@keithamus - Should I bump the version number and push a version tag, so npm gets updated?  Or will you take care of that?

**Comment by keithamus** [comment]
@BigstickCarpet if you could handle that, that'd be swell 😄
