### ISSUE TITLE
Can you push a new version to npm?

### ISSUE THREAD

**Issue by pvencill** [chaijs/chai-fs#24]
The current version on npm is 0.1.0 which still has a peer dependency on chai < 2. Chai is up to 3.5 now.  I know I can just reference the master branch, but updating npm would be value add for developers.

**Comment by BigstickCarpet** [comment]
@pvencill - My bad.  I meant to do that [last month](https://github.com/chaijs/chai-fs/issues/21), but then I went on holiday and completely forgot about it  😞

PR https://github.com/chaijs/chai-fs/pull/25 fixes this

**Comment by BigstickCarpet** [comment]
Re-opening this issue because PR #25 didn't fully fix the issue.  The CI build is failing due to some failing tests, which is preventing us from publishing to npm.   Working on it.

**Comment by BigstickCarpet** [comment]
Just a status update....

I just fixed this issue in PR #27. Once that's merged, we can publish a new version to npm.

**Comment by BigstickCarpet** [comment]
Chai-FS v1.0.0 has been published to npm. 
https://github.com/chaijs/chai-fs/releases/tag/v1.0.0

**Comment by keithamus** [comment]
Awesome work @BigstickCarpet!
