### ISSUE TITLE
file().and.equal() not working as expected

### ISSUE THREAD

**Issue by pvencill** [chaijs/chai-fs#28]
So for one of my test cases, my setup process (before() hook) is to copy a directory from one place to another.  My application code is then supposed to analyze the copied location and either modify files in that directory or not based on params, so I'm working on testing behavior against a range of inputs.

*Without actually running my application code yet*, I decided to test chai-fs's behavior to make sure that I am using the right assertion, so that if I don't get what I expect I at least know it's my app code and not the assertion library that's causing me grief. 

Well... here's how that worked out. 

As I said I did a full directory copy from 'a' to a new directory 'b'.  I visually inspected to make sure file 'filename' exists in both directories and it looks identical visually.  If I run:

`expect('./a/filename').to.be.a.file('It is a file').and.equal('./b/filename', 'Nope, files are not the same');`

I get an assertion error that the expectation failed (and the second message is the one that shows up).  Not sure how these two files can have different content when the one file was copied unmodified from the other file just before the test. 

Any idea how to debug this, or is this feature not fully implemented yet?

**Comment by BigstickCarpet** [comment]
Several new assertions (such as `file().and.equal()`) have been added to Chai-FS recently, but we haven't published a new version to npm yet (see issue https://github.com/chaijs/chai-fs/issues/24), so the version that's currently published on npm doesn't support these new assertions yet.

The version that's currently on npm is `0.1.0`, which only supports the assertions [listed here](https://github.com/chaijs/chai-fs/blob/120a7b12d8ad160e07cbfd1a16c037ba6d8c047c/README.md)

**Comment by BigstickCarpet** [comment]
Just a status update....

I just pushed PR #27, which fixes the issue that's been preventing us from publishing a new version to npm. Once that PR gets merged, we'll publish Chai-FS v1.0.0.

**Comment by BigstickCarpet** [comment]
Chai-FS v1.0.0 has been published to npm.  `file().and.equal()` should work as expected now.

https://github.com/chaijs/chai-fs/releases/tag/v1.0.0
