### ISSUE TITLE
Doesn't work with latest Chai version

### ISSUE THREAD

**Issue by jescalan** [chaijs/chai-fs#7]
> The package chai does not satisfy its siblings' peerDependencies requirements!
> peerinvalid Peer chai-fs@0.1.0 wants chai@>= 1.6.1 < 2

I'll look into fixing this up with a pull request right now.

**Comment by beraboris** [comment]
Is anyone working on fixing this?

**Comment by zckrs** [comment]
https://github.com/Bartvds/chai-fs/pull/5

**Comment by psmolinsky** [comment]
+1

**Comment by fusepilot** [comment]
Still not working. And #5 is closed now.

**Comment by ajwhite** [comment]
+1

**Comment by sirodoht** [comment]
This project seems dead. Last commit almost a year ago.

This fork looks to continue the effort though I have not tested it yet.
https://github.com/peterkc/chai-fs

**Comment by electricmonk** [comment]
@Bartvds do you plan to keep on maintaining this project?

**Comment by prometheas** [comment]
@Bartvds - bump. This tiny `package.json` update is a long time needed. Please address.

**Comment by prometheas** [comment]
Hey @Bartvds - sorry to be stalking your ass here, but I'm seeing you're active on Github within very recent days :wink:  please just let your intentions be known to the world, or perhaps transfer ownership of the project on npm to someone who cares enough to remedy this small issue?

Many of us have come to depend on this chai plugin.

**Comment by jenius** [comment]
@prometheas if you're looking for a quick fix, i have a fork where it's fixed [here](https://github.com/jenius/chai-fs), you can add it to your `package.json` as `jenius/chai-fs` and it should work fine. I don't use this plugin as heavily anymore, so probably wouldn't be the best choice for a maintainer, but I am active and respond to stuff if that helps haha

**Comment by prometheas** [comment]
Appreciate the heads up, sir. Perhaps an inclination to accept pull requests might go far enough on what the community would ever need from you :laughing:

**Comment by jenius** [comment]
@prometheas hah, if thats all thats needed, I'm in :+1:

**Comment by goliney** [comment]
Have you guys looked at this repo: https://github.com/tschaub/mock-fs ? It seems to be not dead.

**Comment by meeber** [comment]
I think this was resolved via #8. Can we close this? @keithamus
